### ISSUE TITLE
Why tie this proposal to "expanding the standard library?"

### ISSUE THREAD

**Issue by domenic** [littledan/proposal-idl#1]
I think the sections of this document, and of the corresponding slide, which argue for expanding the standard library and for doing so in TC39, are needlessly distracting and controversial, and are likely to suck up a lot of discussion time. I think a better approach might be to talk about consistency within the current standard library, and about how every time we add something (which we do, periodically) it's a pain. Instead of making it so that we first have to debate the premise of a large TC39-guided standard library expansion movement, before getting to the interesting discussions of the benefits of an IDL.

**Comment by littledan** [comment]
Thanks for the advice.

We have been continuing to expand the standard library in TC39, e.g. in Intl. I think this has been working well and we should keep doing it. This proposal aims to solve problems encountered in that process. The benefit to explain existing things in WebIDL is less than the benefit to new library features, IMO.

Do you have any particular counter-arguments in mind that I should work to steer clear of? Of course I am not proposing that all library development happen in TC39; I don't think this would make any sense.

**Comment by littledan** [comment]
OK, I've removed the sections of the explainer that I think you're referring to, and moved the slides to a "bonus slides" section. You're right, that we don't want to bring in the whole question of, "how minimal should the standard library be?", and that IDL would have a big benefit if we continue developing at the current pace.
