### ISSUE TITLE
"It is not currently at a stage in TC39."

### ISSUE THREAD

**Issue by jmdyck** [littledan/proposal-idl#4]
The first para says "It is not currently at a stage in TC39."
But everything else says that it's at stage 1.

**Comment by littledan** [comment]
Right, the readme should say Stage 1.

**Comment by gesa** [comment]
since it's stage 1 now, this should also be bumped over to the tc39 org. would you be so kind as to transfer ownership to tc39-transfer?

**Comment by ExE-Boss** [comment]
This&nbsp;looks&nbsp;done to&nbsp;me&nbsp;now.
